FROM python:3.13

# ENV VIRTUAL_ENV=/code/.venv
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/root/.local/bin:$PATH"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /code

COPY pyproject.toml uv.lock /code/
ADD https://astral.sh/uv/install.sh /uv-installer.sh


RUN sh /uv-installer.sh  
RUN rm /uv-installer.sh 
RUN uv sync
