FROM python:3.9

# ENV VIRTUAL_ENV=/code/.venv
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/root/.local/bin:$PATH"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /code

COPY pyproject.toml uv.lock /code/

RUN curl -LsSf https://astral.sh/uv/install.sh | sh \
    && uv sync --frozen
