version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:9.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run ./manage.py test --failfast
  build-and-lint: 
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run linters
          command: poetry run pre-commit run --all-files

workflows:
  sample: 
    jobs:
      - build-and-test
      - build-and-lint
