version: 2.1

orbs:
  python: circleci/python@3

jobs:
  test: 
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:17.4
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies with uv
          command: uv sync --frozen
      - run:
          name: Run tests
          command: uv run ./manage.py test -v 2 --failfast
  lint: 
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies with uv
          command: uv sync --frozen
      - run:
          name: Run linters
          command: uv run pre-commit run --all-files
  css: 
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies with uv
          command: uv sync --frozen
      - run:
          name: Compile css
          command: uv run ./manage.py custom_bootstrap5

workflows:
  ci: 
    jobs:
      - test
      - lint
      - css
