# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 20:28
from __future__ import unicode_literals

from django.contrib.flatpages.models import FlatPage
from django.contrib.sites.models import Site
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = []
