# Generated by Django 3.2.11 on 2023-04-04 14:49

import django.db.models.deletion
from django.db import migrations, models

ORDER = (
    "United States",
    "Canada",
    "United Kingdom",
    "Worldwide",
    "Coming soon (Agreements in process)",
)

DATA = {
    "United States": (
        "American University",
        "Boston Children's Hospital",
        "Boston College",
        "Boston University",
        "Brown University",
        "Bucknell University",
        "Clark University",
        "Cornell University",
        "Davidson College",
        "Duke University",
        "Duke University School of Medicine",
        "East Tennessee State University",
        "Emory University",
        "Florida International University",
        "Fordham University",
        "Franklin & Marshall College",
        "George Mason University",
        "Harvard University",
        "Harvard Graduate School of Education",
        "Haskins Laboratories, Yale University",
        "Hope College",
        "Kennedy Kreiger Institute, Johns Hopkins University",
        "Kent State University",
        "Loyola University Chicago",
        "Massachusetts Institute of Technology",
        "Montclair State University",
        "Morgan State University",
        "New York University",
        "Northeastern University",
        "Northern Illinois University",
        "Northwestern University",
        "Rutgers University - New Brunswick",
        "Rutgers University - Newark",
        "Sacred Heart University",
        "Skidmore College",
        "Smith College",
        "Stanford University",
        "Stony Brook University",
        "The New School",
        "University at Buffalo, The State University of New York",
        "University of California, Berkeley",
        "University of California, Davis",
        "University of California, Los Angeles",
        "University of California, Riverside",
        "University of California, San Diego",
        "University of Chicago",
        "University of Illinois, Urbana-Champaign",
        "University of Kansas",
        "University of Louisville",
        "University of Maryland, College Park",
        "University of Massachusetts, Lowell",
        "University of Massachusetts, Amherst",
        "University of North Carolina, Asheville",
        "University of Oregon",
        "University of Pennsylvania",
        "University of South Florida",
        "University of Southern California",
        "University of Texas, Austin",
        "University of Texas, Dallas",
        "University of Virginia",
        "University of Washington",
        "University of Wisconsin, Madison",
        "Virginia Tech",
        "Wellesley College",
        "Williams College",
        "Yale School of Medicine",
        "Yale University",
        "Yeshiva University - Stern College for Women",
    ),
    "Canada": (
        "Brock University",
        "Concordia University",
        "Dalhousie University",
        "McGill University",
        "McMasters University",
        "Ryerson University",
        "University of British Columbia",
        "University of Toronto",
        "University of Waterloo",
    ),
    "United Kingdom": (
        "Birkbeck, University of London",
        "Goldsmiths, University of London",
        "Great Ormond Street Institute of Child Health (UCL)",
        "Nottingham University",
        "St Andrews University",
        "Ulster University",
        "University College London",
        "University of East Anglia",
        "University of Edinburgh",
        "University of Essex",
        "University of Lincoln",
    ),
    "Worldwide": (
        "Aix-Marseille Université/CNRS (France)",
        "Boğaziçi University (Turkey)",
        "CEMIC-CONICET (Argentina)",
        "Leiden University (Netherlands)",
        "Max Planck Institute for Human Cognitive and Brain Sciences (Germany)",
        "University of Tokyo 東京大学 (Japan)",
        "Western Sydney University (Australia)",
    ),
    "Coming soon (Agreements in process)": (
        "Carnegie Mellon University",
        "Florida State University",
        "Hunter College",
        "Indiana University",
        "John Jay College of Criminal Justice and CUNY Graduate Center",
        "Max Planck Institute for Psycholinguistics",
        "Mount Sinai Hospital",
        "Oklahoma State University",
        "Oxford University",
        "Temple University",
        "University of Arkansas",
        "University of Cambridge",
        "University of Minnesota, Twin Cities",
        "University of North Carolina, Greensboro",
        "University of Pittsburgh",
        "Vanderbilt University",
        "Villanova University",
        "Western Washington University",
    ),
}


def populate_instition_section(apps, schema_editor):
    institution_section = apps.get_model("web", "InstitutionSection")
    for section_name in DATA.keys():
        institution_section(name=section_name, order=ORDER.index(section_name)).save()


def populate_instition(apps, schema_editor):
    institution = apps.get_model("web", "Institution")
    institution_section = apps.get_model("web", "InstitutionSection")
    for section_name, institution_names in DATA.items():
        institution_section_obj = institution_section.objects.get(name=section_name)
        for institution_name in institution_names:
            institution(name=institution_name, section=institution_section_obj).save()


def do_nothing(apps, schema_editor):
    """Data migrations can be just removed from the database, so nothing actually needs to be done.  This function allows a reversal of the migration."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("web", "0001_create_initial_flatpages"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.institutionsection",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_instition_section, reverse_code=do_nothing),
        migrations.RunPython(populate_instition, reverse_code=do_nothing),
    ]
