# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models
import project.fields.datetime_aware_jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollaboratorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_profile', related_query_name='collaborator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_children', models.PositiveSmallIntegerField(default=1, verbose_name='number of children')),
                ('child_birthdays', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None, verbose_name="children's birthdays")),
                ('languages_spoken_at_home', models.TextField(verbose_name='langues spoken at home')),
                ('number_of_guardians', models.PositiveIntegerField()),
                ('number_of_guardians_explanation', models.TextField()),
                ('race_identification', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('education_level', models.CharField(choices=[('none', 'None'), ('elem', 'Elementary'), ('hs', 'Some High School'), ('hsd', 'High School Degree'), ('col', 'Some College'), ('assoc', 'Associates Degree'), ('bach', "Bachelor's Degree"), ('mast', "Master's Degree"), ('prof', 'Professional Degree'), ('doct', 'Doctorate')], max_length=5)),
                ('spouse_education_level', models.CharField(choices=[('none', 'None'), ('elem', 'Elementary'), ('hs', 'Some High School'), ('hsd', 'High School Degree'), ('col', 'Some College'), ('assoc', 'Associates Degree'), ('bach', "Bachelor's Degree"), ('mast', "Master's Degree"), ('prof', 'Professional Degree'), ('doct', 'Doctorate')], max_length=5)),
                ('number_of_books', models.IntegerField()),
                ('additional_comments', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('density', models.TextField()),
                ('extra', project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', related_query_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
