# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_identicon',
            field=models.TextField(default='', verbose_name='identicon'),
            preserve_default=False,
        ),
    ]
