# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 18:50
from __future__ import unicode_literals

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from accounts.models import DemographicData, Organization, User
from studies.models import Response, Study, StudyLog

permission_models = [
    Study,
    StudyLog,
    Organization,
    User,
    DemographicData,
    Response,
]

GROUP_NAME = "COS_ADMIN"


def create_cos_admin_group_and_populate_permissions(*args, **kwargs):
    cos_admin_group = Group.objects.create(name=GROUP_NAME)
    for model in permission_models:
        permissions = Permission.objects.filter(
            content_type=ContentType.objects.get_for_model(model)
        )
        cos_admin_group.permissions.add(*permissions)


def goodbye_cos_admin_group(*args, **kwargs):
    Group.objects.filter(name=GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.RunPython(
            create_cos_admin_group_and_populate_permissions, goodbye_cos_admin_group
        )
    ]
