# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auto_20170607_1800"),
        ("studies", "0002_auto_20170607_1800"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile"),
        migrations.AddField(
            model_name="child",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                related_query_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
