# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0004_auto_20170607_1800")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        )
    ]
