# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170427_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('is_admin', 'Organization Administrator'), ('can_add_researchers', 'Can Add Researchers'), ('can_approve_studies', 'Can Approve Studies'), ('can_disable_studies', 'Can Disable Studies'), ('can_view', 'Can View'))},
        ),
    ]
