# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170428_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('is_admin', 'Organization Administrator'), ('can_add_researchers', 'Can Add Researchers'), ('can_approve_studies', 'Can Approve Studies'), ('can_disable_studies', 'Can Disable Studies'), ('can_view', 'Can View'), ('can_add_study', 'Can Add Study'))},
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='identifier'),
        ),
    ]
