# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170417_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', related_query_name='collaborator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='ParticipantProfile',
            new_name='Participant',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollaboratorProfile',
        ),
    ]
