# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170418_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(default='Family Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(default='Given Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', related_query_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
