# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170622_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
