# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_auto_20170622_1504")]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("can_view_organization", "Can View Organization"),
                    ("can_edit_organization", "Can Edit Organization"),
                    ("can_create_organization", "Can Create Organization"),
                    ("can_remove_organization", "Can Remove Organization"),
                )
            },
        )
    ]
