# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170419_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
