# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_auto_20170626_1811"),
        ("accounts", "0007_organization_uuid"),
    ]

    operations = []
