# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170615_1524'),
        ('accounts', '0007_auto_20170626_1811'),
    ]

    operations = [
    ]
