# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_cos_admin_group_and_assign_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('can_view', 'Can View'), ('can_edit', 'Can Edit'), ('can_create', 'Can Create'), ('can_remove', 'Can Remove'))},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_create', 'Can Create'), ('can_view', 'Can View'), ('can_edit', 'Can Edit'), ('can_remove', 'Can Remove'), ('can_view_permissions', 'Can View Permissions'), ('can_edit_permissions', 'Can Edit Permissions'))},
        ),
    ]
