# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='identifier'),
        ),
    ]
