# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170710_1449'),
        ('accounts', '0008_merge_20170710_1803'),
    ]

    operations = [
    ]
