# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0012_auto_20170718_2114")]

    operations = [
        migrations.RemoveField(model_name="user", name="email_opt_out"),
        migrations.AddField(
            model_name="user",
            name="email_personally",
            field=models.BooleanField(default=True),
        ),
    ]
