# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0014_auto_20170726_1403")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_researcher",
            field=models.BooleanField(default=False),
        )
    ]
