# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_is_researcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
