# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_create_mit_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_researcher',
            field=models.BooleanField(default=False),
        ),
    ]
