# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_create_mit_organization"),
        ("accounts", "0018_auto_20170805_2012"),
    ]

    operations = []
