# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0020_auto_20170807_1545")]

    operations = [
        migrations.AlterField(
            model_name="demographicdata",
            name="number_of_guardians_explanation",
            field=models.TextField(blank=True),
        )
    ]
