# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20170808_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
