# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicdata',
            name='lookit_referrer',
            field=models.TextField(blank=True),
        ),
    ]
