# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0026_auto_20170823_1352")]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_personally",
            new_name="email_response_questions",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="email_results_published",
            new_name="email_study_updates",
        ),
    ]
