# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0029_user_former_lookit_id")]

    operations = [
        migrations.AddField(
            model_name="child",
            name="former_lookit_profile_id",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
