# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_child_former_lookit_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='given_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
