# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 04:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0034_auto_20170911_1832")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linked_former_lookit_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        )
    ]
