# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("accounts", "0039_auto_20180219_1259")]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("email_sent", models.DateTimeField(default=None, null=True)),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="messages", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
