# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 16:30
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models
from django.utils.translation import gettext as _
from model_utils import Choices

# Deprecating
AGE_AT_BIRTH_CHOICES = Choices(
    ("na", _("Not sure or prefer not to answer")),
    ("<24", _("Under 24 weeks")),
    ("24", _("24 weeks")),
    ("25", _("25 weeks")),
    ("26", _("26 weeks")),
    ("27", _("27 weeks")),
    ("28", _("28 weeks")),
    ("29", _("29 weeks")),
    ("30", _("30 weeks")),
    ("31", _("31 weeks")),
    ("32", _("32 weeks")),
    ("33", _("33 weeks")),
    ("34", _("34 weeks")),
    ("35", _("35 weeks")),
    ("36", _("36 weeks")),
    ("37", _("37 weeks")),
    ("38", _("38 weeks")),
    ("39", _("39 weeks")),
    ("40>", _("40 or more weeks")),
)


GESTATIONAL_AGE_CHAR_TO_INT_MAPPING = {
    "": None,
    "0": None,
    "na": None,
    "23": 0,
    "<24": 0,
    "24": 1,
    "25": 2,
    "26": 3,
    "27": 4,
    "28": 5,
    "29": 6,
    "30": 7,
    "31": 8,
    "32": 9,
    "33": 10,
    "34": 11,
    "35": 12,
    "36": 13,
    "37": 14,
    "38": 15,
    "39": 16,
    "40>": 17,
}


REVERSE_GESTATIONAL_AGE_MAPPING = {
    v: k for k, v in GESTATIONAL_AGE_CHAR_TO_INT_MAPPING.items()
}


def _forwards_migrate_ga_birth_char_field_to_int(apps, schema_editor):

    ChildModel = apps.get_model("accounts", "Child")

    for child in ChildModel.objects.all():
        child.gestational_age_at_birth = GESTATIONAL_AGE_CHAR_TO_INT_MAPPING[
            child.age_at_birth
        ]
        child.save()


def _backwards_reverse_int_field_to_char(apps, schema_editor):
    ChildModel = apps.get_model("accounts", "Child")

    for child in ChildModel.objects.all():
        child.age_at_birth = REVERSE_GESTATIONAL_AGE_MAPPING[
            child.gestational_age_at_birth
        ]
        child.save()


class Migration(migrations.Migration):

    dependencies = [("accounts", "0040_add_message_model")]

    operations = [
        migrations.AddField(
            model_name="child",
            name="gestational_age_at_birth",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (None, "Not sure or prefer not to answer"),
                    (0, "Under 24 weeks"),
                    (1, "24 weeks"),
                    (2, "25 weeks"),
                    (3, "26 weeks"),
                    (4, "27 weeks"),
                    (5, "28 weeks"),
                    (6, "29 weeks"),
                    (7, "30 weeks"),
                    (8, "31 weeks"),
                    (9, "32 weeks"),
                    (10, "33 weeks"),
                    (11, "34 weeks"),
                    (12, "35 weeks"),
                    (13, "36 weeks"),
                    (14, "37 weeks"),
                    (15, "38 weeks"),
                    (16, "39 weeks"),
                    (17, "40 or more weeks"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.RunPython(
            _forwards_migrate_ga_birth_char_field_to_int,
            reverse_code=_backwards_reverse_int_field_to_char,
        ),
        migrations.AlterField(  # manually added to enable migration reversal, see https://stackoverflow.com/a/28879030
            model_name="child",
            name="age_at_birth",
            field=models.CharField(
                max_length=25, choices=AGE_AT_BIRTH_CHOICES, default="na"
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(model_name="child", name="age_at_birth"),
        migrations.AddField(
            model_name="child",
            name="existing_conditions",
            field=bitfield.models.BitField(
                (
                    ("autism_spectrum_disorder", "Autism Spectrum Disorder"),
                    ("aspergers_syndrome", "Asperger's Syndrome"),
                    ("down_syndrome", "Down Syndrome"),
                    ("williams_syndrome", "Williams Syndrome"),
                    ("stroke", "Stroke"),
                    ("blind", "Blind"),
                    ("visual_impairment", "Visual Impairment"),
                    ("deaf", "Deaf"),
                    ("hearing_impairment", "Hearing Impairment"),
                    ("dyslexia", "Dyslexia"),
                    (
                        "attention_deficit_hyperactivity_disorder",
                        "Attention Deficit/Hyperactivity Disorder",
                    ),
                    ("learning_disability", "Learning Disability"),
                    ("generalized_anxiety_disorder", "Generalized Anxiety Disorder"),
                    ("obsessive_compulsive_disorder", "Obsessive-Compulsive Disorder"),
                    ("panic_disorder", "Panic Disorder"),
                    (
                        "post_traumatic_stress_disorder",
                        "Post-Traumatic Stress Disorder",
                    ),
                    (
                        "social_phobia_social_anxiety_disorder",
                        "Social Phobia/Social Anxiety Disorder",
                    ),
                    ("depression", "Depression"),
                    ("other_mood_disorder", "Other Mood Disorder"),
                    ("allergies", "Allergies"),
                    ("fetal_alcohol_syndrome", "Fetal Alcohol Syndrome"),
                    ("epilepsy", "Epilepsy"),
                    ("diabetes", "Diabetes"),
                    (
                        "other_chronic_medical_condition",
                        "Other Chronic Medical Condition",
                    ),
                    ("other_genetic_condition", "Other Genetic Condition"),
                    (
                        "gifted_advanced_learning_needs",
                        "Gifted/Advanced learning needs",
                    ),
                    ("adopted", "Adopted"),
                    (
                        "multiple birth",
                        "Multiple Birth (twin, triplet, or higher order)",
                    ),
                    ("has_older_sibling", "Has at least one older sibling"),
                    ("has_younger_sibling", "Has at least one younger sibling"),
                ),
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="languages_spoken",
            field=bitfield.models.BitField(
                (
                    ("cmn", "Mandarin"),
                    ("es", "Spanish"),
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("bn", "Bengali"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("ja", "Japanese"),
                    ("lah", "Western Punjabi"),
                    ("mr", "Marathi"),
                    ("te", "Telugu"),
                    ("wuu", "Wu"),
                    ("tr", "Turkish"),
                    ("ko", "Korean"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("vi", "Vietnamese"),
                    ("ta", "Tamil"),
                    ("yue", "Yue"),
                    ("ur", "Urdu"),
                    ("jv", "Javanese"),
                    ("it", "Italian"),
                    ("egy", "Egyptian Spoken Arabic"),
                    ("gu", "Gujarati"),
                    ("pes", "Iranian Persian"),
                    ("bho", "Bhojpuri"),
                    ("nan", "Min Nan"),
                    ("hak", "Hakka"),
                    ("cjy", "Jinyu"),
                    ("ha", "Hausa"),
                    ("kn", "Kannada"),
                    ("id", "Indonesian"),
                    ("pl", "Polish"),
                    ("yo", "Yoruba"),
                    ("hsn", "Xiang Chinese"),
                    ("ml", "Malayalam"),
                    ("or", "Odia"),
                    ("mai", "Maithili"),
                    ("my", "Burmese"),
                    ("su", "Sunda"),
                    ("mor", "Moroccan Spoken Arabic"),
                    ("uk", "Ukrainian"),
                    ("ig", "Igbo"),
                    ("uzn", "Northern Uzbek"),
                    ("sd", "Sindhi"),
                    ("ro", "Romanian"),
                    ("tl", "Tagalog"),
                    ("nl", "Dutch"),
                    ("gan", "Gan"),
                    ("am", "Amharic"),
                    ("pbu", "Northern Pashto"),
                    ("mag", "Magahi"),
                    ("th", "Thai"),
                    ("skr", "Saraiki"),
                    ("km", "Khmer"),
                    ("hne", "Chhattisgarhi"),
                    ("so", "Somali"),
                    ("ms", "Malay"),
                    ("ceb", "Cebuano"),
                ),
                default=0,
            ),
        ),
    ]
