# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0041_add_existing_conditions")]

    operations = [migrations.RemoveField(model_name="child", name="age_at_birth")]
