# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 17:30
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations

from studies.fields import CONDITIONS, LANGUAGES


class Migration(migrations.Migration):

    dependencies = [("accounts", "0041_add_existing_conditions")]

    operations = [
        # A dirty trick: https://yunojuno.silvrback.com/pro-tip-django-choices-and-migrations
        migrations.AlterField(
            model_name="child",
            name="existing_conditions",
            field=bitfield.models.BitField((lambda: CONDITIONS)(), default=0),
        ),
        migrations.AlterField(
            model_name="child",
            name="languages_spoken",
            field=bitfield.models.BitField((lambda: LANGUAGES)(), default=0),
        ),
    ]
