# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0041_add_existing_conditions")]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="multiple_birth_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twin", "Twin"),
                    ("triplet", "Triplet"),
                    ("quadruplet", "Quadruplet"),
                    ("quintuplet", "Quintuplet"),
                    ("sextuplet", "Sextuplet"),
                    ("septuplet", "Septuplet"),
                    ("octuplet", "Octuplet"),
                ],
                max_length=16,
                null=True,
            ),
        )
    ]
