# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0043_gestational-age-can-be-blank")]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={
                "ordering": ["-birthday"],
                "permissions": [
                    (
                        "can_view_all_children_in_analytics",
                        "Can view all children in analytics",
                    )
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("can_view_organization", "Can View Organization"),
                    ("can_edit_organization", "Can Edit Organization"),
                    ("can_create_organization", "Can Create Organization"),
                    ("can_remove_organization", "Can Remove Organization"),
                    ("can_view_experimenter", "Can View Experimenter"),
                    ("can_view_analytics", "Can View Analytics"),
                ),
            },
        ),
    ]
