# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-13 15:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0065_new-lab-study-perms-model-defs"),
        ("accounts", "0046_catch-up-migrations-to-current"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                related_query_name="member",
                to="studies.Lab",
            ),
        )
    ]
