# Generated by Django 3.0.7 on 2020-07-01 18:27

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_remove_user_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAuthenticatorTOTP",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="_otp",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        db_index=True, default=pyotp.random_base32, max_length=16
                    ),
                ),
            ],
        ),
    ]
