# Generated by Django 3.0.7 on 2020-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_two_factor_auth_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="children_of_interest",
            field=models.ManyToManyField(
                related_name="notifications", to="accounts.Child"
            ),
        ),
    ]
