# Generated by Django 3.0.7 on 2020-08-19 21:14

from django.db import migrations
from django.db.models import Q

ten_am_crontab_schedule_dict = dict(
    minute="0", hour="10", day_of_week="*", day_of_month="*", month_of_year="*"
)
send_announcement_emails_periodic_task_spec = dict(
    name="Send Study Announcement Emails", task="studies.tasks.send_announcement_emails"
)


def create_scheduled_jobs(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    ten_am_crontab_schedule, created = CrontabSchedule.objects.get_or_create(
        **ten_am_crontab_schedule_dict
    )

    send_announcement_emails_periodic_task_spec.update(
        dict(crontab=ten_am_crontab_schedule)
    )
    announcement_emails_periodic_task, created = PeriodicTask.objects.get_or_create(
        **send_announcement_emails_periodic_task_spec
    )


def remove_scheduled_jobs(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    CrontabSchedule.objects.filter(**ten_am_crontab_schedule_dict).delete()
    PeriodicTask.objects.filter(
        Q(**send_announcement_emails_periodic_task_spec)
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0050_child_message_join_table_for_announcement_emails"),
    ]

    operations = [migrations.RunPython(create_scheduled_jobs, remove_scheduled_jobs)]
