# Generated by Django 3.0.14 on 2021-07-09 20:01

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_daily_announcement_email_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleauthenticatortotp",
            name="secret",
            field=models.CharField(
                db_index=True, default=pyotp.random_base32, max_length=32
            ),
        ),
    ]
