# Generated by Django 3.0.7 on 2021-07-15 19:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210119_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
    ]
