# Generated by Django 3.1.13 on 2021-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_increase_secret_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographicdata",
            name="extra",
            field=models.JSONField(null=True),
        ),
    ]
