# Generated by Django 3.2.9 on 2022-05-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_update_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicdata',
            name='education_level_free',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
