# Generated by Django 3.2.11 on 2022-06-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_update_jsonfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demographicdata",
            old_name="languages_spoken_at_home",
            new_name="old_languages_spoken_at_home",
        ),
        migrations.RenameField(
            model_name="demographicdata",
            old_name="number_of_books",
            new_name="old_number_of_books",
        ),
        migrations.RenameField(
            model_name="demographicdata",
            old_name="number_of_guardians_explanation",
            new_name="old_number_of_guardians_explanation",
        ),
        migrations.RenameField(
            model_name="demographicdata",
            old_name="spouse_education_level",
            new_name="old_spouse_education_level",
        ),
    ]
