# Generated by Django 3.2.11 on 2023-11-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_update_demo_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="birthday",
            field=models.DateField(),
        ),
    ]
