# Generated by Django 3.2.11 on 2023-01-25 16:20

import operator
from functools import reduce

import bitfield.models
from django.db import migrations

FIELDS = (
    ("white", "White"),
    ("hisp", "Hispanic, Latino, or Spanish origin"),
    ("black", "Black or African American"),
    ("asian", "Asian"),
    ("native", "American Indian or Alaska Native"),
    ("mideast-naf", "Middle Eastern or North African"),
    ("hawaiian-pac-isl", "Native Hawaiian or Other Pacific Islander"),
    ("other", "Another race, ethnicity, or origin"),
)


def encode_ethnicity(apps, schema_editor):
    fields = [v[0] for v in FIELDS]
    for demo_data in apps.get_model("accounts", "DemographicData").objects.all():
        masks = (
            2 ** fields.index(v)
            for v in demo_data.us_race_ethnicity_identification
            if v in fields
        )
        encoded_value = reduce(operator.__or__, masks, 0)
        demo_data.us_race_ethnicity_identification = [encoded_value]
        demo_data.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_update_demo_fields"),
    ]

    operations = [
        migrations.RunPython(encode_ethnicity),
        migrations.AlterField(
            model_name="demographicdata",
            name="us_race_ethnicity_identification",
            field=bitfield.models.BitField(FIELDS, default=0),
        ),
    ]
