# Generated by Django 3.2.11 on 2024-01-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_alter_child_birthday_not_null_or_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_spam",
            field=models.BooleanField(
                default=False,
                help_text="If account is spam, please set to inactive and all email options to false.",
            ),
        ),
    ]
