# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 15:34
from __future__ import unicode_literals
from django.conf import settings

import os

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osf_oauth2_adapter", "0001_make_human_group"),
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = []
