# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project.fields.datetime_aware_jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frames', models.ManyToManyField(related_name='study', to='studies.Frame')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame', to='studies.FrameType'),
        ),
    ]
