# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('retracted', 'Retracted'), ('approved', 'Approved'), ('active', 'Active'), ('paused', 'Paused'), ('deactivated', 'Deactivated')], default='created', max_length=25),
        ),
    ]
