# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auto_20170607_1800"),
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="response", name="profile"),
        migrations.AddField(
            model_name="response",
            name="child",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.Child",
            ),
            preserve_default=False,
        ),
    ]
