# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:41
from __future__ import unicode_literals

from django.db import migrations
import project.fields.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='study',
            name='frames',
        ),
        migrations.AddField(
            model_name='study',
            name='blocks',
            field=project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.DeleteModel(
            name='FrameType',
        ),
    ]
