# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20170418_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='name',
            field=models.CharField(default='Study Name', max_length=255),
            preserve_default=False,
        ),
    ]
