# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='is_active',
        ),
    ]
