# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_remove_study_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='action',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='action',
            field=models.CharField(max_length=128),
        ),
    ]
