# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20170616_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
