# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20170420_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
