# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20170425_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', related_query_name='logs', to='studies.Study'),
        ),
    ]
