# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:22
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0004_auto_20170616_0244")]

    operations = [
        migrations.AddField(
            model_name="response",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="responselog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="studylog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
