# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20170616_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='max_age',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='study',
            name='min_age',
            field=models.TextField(default=''),
        ),
    ]
