# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_auto_20170426_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='studies.Study'),
        ),
    ]
