# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("studies", "0005_auto_20170623_1702")]

    operations = [
        migrations.AddField(
            model_name="study", name="comments", field=models.TextField(default="")
        )
    ]
