# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0006_study_comments")]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="comments",
            field=models.TextField(blank=True, null=True),
        )
    ]
