# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_auto_20170426_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(default="Pooping rainbow while flying in a toasted bread costume in space licks your face catch mouse and gave it as a present or chase the pig around the house or hide when guests come over toy mouse squeak roll over. Run outside as soon as door open refuse to drink water except out of someone's glass. Destroy the blinds destroy the blinds yet going to catch the red dot today going to catch the red dot today. Tuxedo cats always looking dapper roll over and sun my belly paw at your fat belly, destroy the blinds stare at the wall, play with food and get confused by dust yet leave fur on owners clothes. Chase the pig around the house. Purr intrigued by the shower intently sniff hand."),
            preserve_default=False,
        ),
    ]
