# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_study_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='study',
            name='long_description',
            field=models.TextField(default="Hide head under blanket so no one can see plan steps for world domination for catch mouse and gave it as a present with tail in the air. Hunt by meowing loudly at 5am next to human slave food dispenser the dog smells bad, so favor packaging over toy. Pose purrfectly to show my beauty go into a room to decide you didn't want to be in there anyway russian blue so stretch hide at bottom of staircase to trip human asdflkjaertvlkjasntvkjn (sits on keyboard) shake treat bag. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff chase after silly colored fish toys around the house immediately regret falling into bathtub or my left donut is missing, as is my right claws in your leg or why must they do that, chase red laser dot. Stand in front of the computer screen destroy couch as revenge so refuse to drink water except out of someone's glass."),
            preserve_default=False,
        ),
    ]
