# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_auto_20170424_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'permissions': (('view_response', 'View Response'),)},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': (('view_study', 'View Study'), ('edit_study', 'Edit Study'), ('can_respond', 'Can Respond?'))},
        ),
        migrations.AddField(
            model_name='responselog',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='studies.Response'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studylog',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='studies.Study'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='studies', related_query_name='study', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
