# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_auto_20170505_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='criteria',
            field=models.TextField(default='American bobtail savannah tiger norwegian forest manx maine coon but ragdoll. Mouser ragdoll. Turkish angora cornish rex.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
