# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_auto_20170505_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='duration',
            field=models.TextField(default='10 minutes'),
            preserve_default=False,
        ),
    ]
