# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_auto_20170629_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='action',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='action',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
