# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_study_contact_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': (('can_view', 'View Study'), ('can_edit', 'Edit Study'), ('can_submit', 'Submit Study'), ('can_respond', 'Can Respond'))},
        ),
    ]
