# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_auto_20170705_2009'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='responselog',
            index_together=set([('response', 'action')]),
        ),
        migrations.AlterIndexTogether(
            name='studylog',
            index_together=set([('study', 'action')]),
        ),
    ]
