# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_auto_20170509_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
