# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_study_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
