# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_auto_20170705_2017'),
        ('studies', '0005_response_date_modified'),
    ]

    operations = [
    ]
