# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0005_auto_20170623_2022"),
        ("studies", "0013_auto_20170705_2017"),
    ]

    operations = []
