# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_study_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
