# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0014_merge_20170707_1801")]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
