# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_auto_20170517_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': (('can_view', 'Can View'), ('can_create', 'Can Create'), ('can_edit', 'Can Edit'), ('can_remove', 'Can Remove'), ('can_activate', 'Can Activate'), ('can_deactivate', 'Can Deactivate'), ('can_pause', 'Can Pause'), ('can_resume', 'Can Resume'), ('can_approve', 'Can Approve'), ('can_submit', 'Can Submit'), ('can_retract', 'Can Retract'), ('can_resubmit', 'Can Resubmit'), ('can_edit_permissions', 'Can Edit Permissions'), ('can_view_permissions', 'Can View Permissions'), ('can_view_responses', 'Can View Responses'), ('can_view_video_responses', 'Can View Video Responses'), ('can_view_demographics', 'Can View Demographics'))},
        ),
    ]
