# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_auto_20170710_1449'),
        ('studies', '0014_merge_20170710_1420'),
    ]

    operations = [
    ]
