# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_merge_20170711_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='exit_url',
            field=models.URLField(default=''),
        ),
    ]
