# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0005_auto_20170628_1749"),
        ("studies", "0020_auto_20170725_1654"),
    ]

    operations = []
