# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:19
from __future__ import unicode_literals

from django.db import migrations

import project.fields.datetime_aware_jsonfield


class Migration(migrations.Migration):
    dependencies = [("studies", "0020_auto_20170725_1654")]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="structure",
            field=project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(
                default={"frames": {}, "sequence": []}
            ),
        )
    ]
