# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0021_merge_20170731_2221"),
        ("studies", "0021_auto_20170809_1719"),
    ]

    operations = []
