# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("studies", "0022_auto_20170815_2241")]

    operations = [migrations.RemoveField(model_name="responselog", name="extra")]
