# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0023_remove_responselog_extra"),
        ("studies", "0022_merge_20170810_1600"),
    ]

    operations = []
