# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0023_remove_responselog_extra"),
        ("studies", "0023_auto_20170817_1400"),
    ]

    operations = []
