# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 18:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import project.fields.datetime_aware_jsonfield

study_name = 'Ember Frame Player (default)'
study_id = None


def make_default_study_type(apps, schema_editor):
    StudyType = apps.get_model('studies.StudyType')
    st, created = StudyType.objects.get_or_create(
        name=study_name,
        configuration={
            # task module should have a build_experiment method decorated as a
            # celery task that takes a study uuid and a preview kwarg which
            # defaults to true
            "task_module": "studies.tasks",
            "metadata": {
                # defines the default metadata fields for that type of study
                "fields": {
                    "addons_repo_url": settings.EMBER_ADDONS_REPO,
                    "last_known_player_sha": None,
                    "last_known_addons_sha": None
                }
            }
        }
    )
    study_id = st.id


def unmake_default_study_type(apps, schema_editor):
    StudyType = apps.get_model('studies.StudyType')
    StudyType.objects.filter(name=self.study_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0024_merge_20170817_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('configuration', project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(default={'metadata': {'fields': {'addons_repo_url': 'https://github.com/centerforopenscience/exp-addons', 'last_known_addons_sha': None, 'last_known_player_sha': None}}, 'task_module': 'studies.tasks'})),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='last_known_addons_sha',
        ),
        migrations.RemoveField(
            model_name='study',
            name='last_known_player_sha',
        ),
        migrations.RemoveField(
            model_name='study',
            name='remote_folder_url',
        ),
        migrations.AddField(
            model_name='study',
            name='metadata',
            field=project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(default={}),
        ),
        migrations.RunPython(
            make_default_study_type,
            reverse_code=unmake_default_study_type
        ),
        migrations.AddField(
            model_name='study',
            name='study_type',
            field=models.ForeignKey(default=study_id, on_delete=django.db.models.deletion.DO_NOTHING, to='studies.StudyType', verbose_name='type'),
            preserve_default=False,
        ),
    ]
