# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0026_set_study_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studies.StudyType', verbose_name='type'),
        ),
    ]
