# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("studies", "0028_study_preview_url")]

    operations = [
        migrations.RemoveField(model_name="study", name="preview_url"),
        migrations.AddField(
            model_name="study",
            name="previewed",
            field=models.BooleanField(default=False),
        ),
    ]
