# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0029_auto_20170825_1505"),
        ("studies", "0024_merge_20170823_1352"),
    ]

    operations = []
