# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0030_merge_20170827_1909'),
        ('studies', '0030_merge_20170827_1539'),
    ]

    operations = [
    ]
