# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0040_add_scheduled_jobs")]

    operations = [
        migrations.AddField(
            model_name="study", name="built", field=models.BooleanField(default=False)
        )
    ]
