# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-09 05:27
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0042_add_consent_flag_to_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRuling",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("accepted", "accepted"), ("rejected", "rejected")],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "arbiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="consent_rulings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="consent_rulings",
                        to="studies.Response",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("pipe_name", models.CharField(max_length=255, unique=True)),
                ("pipe_numeric_id", models.IntegerField(null=True)),
                ("frame_id", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(null=True)),
                (
                    "extension",
                    models.CharField(
                        choices=[
                            ("mp4", "mp4"),
                            ("ogv", "ogv"),
                            ("ogg", "ogg"),
                            ("flv", "flv"),
                            ("avi)", "avi)"),
                            ("webm", "webm"),
                            ("mpg", "mpg"),
                            ("m4p", "m4p"),
                            ("mpeg", "mpeg"),
                            ("amv", "amv"),
                        ],
                        default="mp4",
                        max_length=5,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "is_consent_footage",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="videos",
                        to="studies.Response",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="videos",
                        to="studies.Study",
                    ),
                ),
            ],
        ),
        migrations.AlterIndexTogether(
            name="consentruling",
            index_together=set([("response", "action"), ("response", "arbiter")]),
        ),
    ]
