# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-05 17:11
from __future__ import unicode_literals

from django.db import migrations
import project.fields.datetime_aware_jsonfield
from django.conf import settings


def set_study_types(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    Study = apps.get_model("studies.Study")
    st, created = StudyType.objects.get_or_create(name="Ember Frame Player (default)")

    st.configuration = {
        "task_module": "studies.tasks",
        "metadata": {
            "fields": {
                "player_repo_url": settings.EMBER_EXP_PLAYER_REPO,
                "last_known_player_sha": None,
            }
        },
    }
    st.save()
    ids = Study.objects.all().update(study_type=st)


def unset_study_types(apps, schema_editor):
    Study = apps.get_model("studies.Study")
    ids = Study.objects.all().update(study_type=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0043_add_video_constructs"),
    ]

    operations = [migrations.RunPython(set_study_types, reverse_code=unset_study_types)]
