# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-05 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def set_study_types(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    Study = apps.get_model("studies.Study")
    st = StudyType.objects.get(name="Ember Frame Player (default)")

    st.configuration = {
        "task_module": "studies.tasks",
        "metadata": {
            "fields": {
                "player_repo_url": settings.EMBER_EXP_PLAYER_REPO,
                "last_known_player_sha": None,
            }
        },
    }
    st.save()

    study_metadata_json = st.configuration["metadata"]["fields"]

    Study.objects.all().update(metadata=study_metadata_json)


def unset_study_types(apps, schema_editor):
    Study = apps.get_model("studies.Study")
    Study.objects.all().update(
        metadata={
            "addons_repo_url": settings.EMBER_ADDONS_REPO,
            "player_repo_url": settings.EMBER_EXP_PLAYER_REPO,
            "last_known_addons_sha": None,
            "last_known_player_sha": None,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0043_add_video_constructs"),
    ]

    operations = [migrations.RunPython(set_study_types, reverse_code=unset_study_types)]
