# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 22:03
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("studies", "0045_add_compensation_description")]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "base_manager_name": "related_manager",
                "permissions": (("can_view_feedback", "Can View Feedback"),),
            },
        ),
        migrations.AlterModelOptions(
            name="response",
            options={
                "base_manager_name": "related_manager",
                "ordering": ["-demographic_snapshot__created_at"],
                "permissions": (("view_response", "View Response"),),
            },
        ),
        migrations.AlterModelManagers(
            name="feedback",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("related_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="response",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("related_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
