# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-31 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("studies", "0050_make_bitfield_migrations_easier")]

    operations = [
        migrations.AddField(
            model_name="study",
            name="criteria_expression",
            field=models.TextField(blank=True),
        )
    ]
