# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("studies", "0053_deprecate-old-eligiblity-form")]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={
                "base_manager_name": "related_manager",
                "ordering": ["-demographic_snapshot__created_at"],
                "permissions": (
                    ("view_response", "View Response"),
                    (
                        "view_all_response_data_in_analytics",
                        "View all response data in analytics",
                    ),
                ),
            },
        )
    ]
