# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0054_new-analytics-permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='salt',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
