# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-20 18:03
from __future__ import unicode_literals
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0056_populate_salt_values")]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="salt",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        )
    ]
