# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-19 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("studies", "0059_auto_20200211_1507")]

    operations = [
        migrations.RemoveField(model_name="study", name="is_previewing"),
        migrations.RemoveField(model_name="study", name="previewed"),
    ]
