# Generated by Django 3.0.5 on 2020-05-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import project.fields.datetime_aware_jsonfield
import studies.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0046_upgrade_django_1_11_to_2_0"),
        ("studies", "0062_study_shared_preview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={
                "base_manager_name": "related_manager",
                "ordering": ["-demographic_snapshot__created_at"],
                "permissions": (
                    (
                        "view_all_response_data_in_analytics",
                        "View all response data in analytics",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="consentruling",
            name="arbiter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_rulings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consentruling",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_rulings",
                to="studies.Response",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="researcher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="studies.Response",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.Child"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="demographic_snapshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.DemographicData",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="responselog",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studies.Response"
            ),
        ),
        migrations.AlterField(
            model_name="responselog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="metadata",
            field=project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(
                default=dict
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="structure",
            field=project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(
                default=studies.models.default_study_structure
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="study_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="studies.StudyType",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="studylog",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                related_query_name="logs",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="studylog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studytype",
            name="configuration",
            field=project.fields.datetime_aware_jsonfield.DateTimeAwareJSONField(
                default=studies.models.default_configuration
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="studies.Response",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="videos",
                to="studies.Study",
            ),
        ),
    ]
