# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-13 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studies.permissions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0008_alter_user_username_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0064_upgrade_django_1_11_to_2_1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("primary_investigator_name", models.CharField(max_length=255)),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=255, verbose_name="Contact Phone"),
                ),
                ("lab_website", models.URLField(verbose_name="Lab Website")),
                ("description", models.TextField(blank=True)),
                ("irb_contact_info", models.TextField(blank=True)),
                (
                    "admin_group",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_to_administer",
                        to="auth.Group",
                    ),
                ),
                (
                    "researcher_group",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_for_researchers",
                        to="auth.Group",
                    ),
                ),
                (
                    "view_group",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_for_viewers",
                        to="auth.Group",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": studies.permissions.LabPermission,
            },
        ),
        migrations.CreateModel(
            name="LabGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studies.Lab"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.Group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Permission",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LabUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studies.Lab"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="StudyGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="StudyUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"abstract": False},
        ),
        migrations.AlterModelOptions(
            name="study",
            options={
                "ordering": ["name"],
                "permissions": studies.permissions.StudyPermission,
            },
        ),
        migrations.AddField(
            model_name="study",
            name="admin_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_to_administer",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="analysis_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_for_analysis",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="design_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_to_design",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="manager_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_to_manage",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="preview_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_to_preview",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="researcher_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_for_research",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="submission_processor_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_for_submission_processing",
                to="auth.Group",
            ),
        ),
        migrations.AddField(
            model_name="studyuserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studies.Study"
            ),
        ),
        migrations.AddField(
            model_name="studyuserobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.Permission"
            ),
        ),
        migrations.AddField(
            model_name="studyuserobjectpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="studygroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studies.Study"
            ),
        ),
        migrations.AddField(
            model_name="studygroupobjectpermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.Group"
            ),
        ),
        migrations.AddField(
            model_name="studygroupobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.Permission"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="lab",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studies",
                related_query_name="study",
                to="studies.Lab",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studyuserobjectpermission",
            unique_together=set([("user", "permission", "content_object")]),
        ),
        migrations.AlterUniqueTogether(
            name="studygroupobjectpermission",
            unique_together=set([("group", "permission", "content_object")]),
        ),
        migrations.AlterUniqueTogether(
            name="labuserobjectpermission",
            unique_together=set([("user", "permission", "content_object")]),
        ),
        migrations.AlterUniqueTogether(
            name="labgroupobjectpermission",
            unique_together=set([("group", "permission", "content_object")]),
        ),
    ]
