# Generated by Django 3.0.7 on 2020-07-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0066_new-lab-study-perms-data-migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="study", name="generator", field=models.TextField(default="")
        ),
        migrations.AddField(
            model_name="study",
            name="use_generator",
            field=models.BooleanField(default=False),
        ),
    ]
