# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 19:33
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q

three_thirty_am_crontab_schedule_dict = dict(
    minute="30", hour="3", day_of_week="*", day_of_month="*", month_of_year="*"
)
cleanup_docker_containers_periodic_task_dict = dict(
    name="Nightly docker container cleanup",
    task="studies.tasks.cleanup_docker_containers",
)


def create_scheduled_jobs(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    three_thirty_am_crontab_schedule, created = CrontabSchedule.objects.get_or_create(
        **three_thirty_am_crontab_schedule_dict
    )
    cleanup_docker_containers_periodic_task_dict.update(
        dict(crontab=three_thirty_am_crontab_schedule)
    )
    (
        cleanup_docker_containers_periodic_task,
        created,
    ) = PeriodicTask.objects.get_or_create(
        **cleanup_docker_containers_periodic_task_dict
    )


def remove_scheduled_jobs(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    CrontabSchedule.objects.filter(**three_thirty_am_crontab_schedule_dict).delete()
    PeriodicTask.objects.filter(
        Q(**cleanup_docker_containers_periodic_task_dict)
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0067_add-generator-fields"),
        ("django_celery_beat", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_scheduled_jobs, remove_scheduled_jobs)]
