# Generated by Django 3.0.14 on 2021-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0069_remove_video_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="study", old_name="long_description", new_name="purpose"
        ),
    ]
