# Generated by Django 3.0.14 on 2021-07-14 19:33

import json

from django.db import migrations


def update_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    ember_frame_player = StudyType.objects.get(name="Ember Frame Player (default)")
    config = json.loads(ember_frame_player.configuration)
    config["metadata"]["fields"] = [
        {
            "name": "player_repo_url",
            "value": "https://github.com/lookit/ember-lookit-frameplayer",
            "input_type": "text",
        },
        {
            "name": "last_known_player_sha",
            "value": None,
            "input_type": "text",
        },
    ]
    ember_frame_player.configuration = config
    ember_frame_player.save()


def revert_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    ember_frame_player = StudyType.objects.get(name="Ember Frame Player (default)")
    config = json.loads(ember_frame_player.configuration)
    config["metadata"]["fields"] = {
        "player_repo_url": "https://github.com/lookit/ember-lookit-frameplayer",
        "last_known_player_sha": None,
    }
    ember_frame_player.configuration = config
    ember_frame_player.save()


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0073_add_study_type_to_response"),
    ]

    operations = [migrations.RunPython(update_config, reverse_code=revert_config)]
