# Generated by Django 3.0.14 on 2021-08-11 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0074_update_config_ember_frame_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="study",
            name="exit_url",
        ),
    ]
