# Generated by Django 3.0.14 on 2021-09-24 14:19

from django.db import migrations


def update_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    external = StudyType.objects.get(name="External")
    external.configuration["metadata"]["fields"] = [
        {"name": "url", "value": "", "input_type": "url"}
    ]
    external.save()


def revert_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    external = StudyType.objects.get(name="External")
    external.configuration["metadata"]["fields"] = [
        {
            "name": "url",
            "value": "",
            "input_type": "url",
        },
        {
            "name": "scheduled",
            "value": False,
            "input_type": "checkbox",
        },
    ]
    external.save()


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0075_remove_exit_url"),
    ]

    operations = [migrations.RunPython(update_config, reverse_code=revert_config)]
