# Generated by Django 3.0.14 on 2021-09-24 14:19

import json

from django.db import migrations


def update_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    external = StudyType.objects.get(name="External")
    config = json.loads(external.configuration)
    config["metadata"]["fields"] = [{"name": "url", "value": "", "input_type": "url"}]
    external.configuration = config
    external.save()


def revert_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    external = StudyType.objects.get(name="External")
    config = json.loads(external.configuration)
    config["metadata"]["fields"] = [
        {
            "name": "url",
            "value": "",
            "input_type": "url",
        },
        {
            "name": "scheduled",
            "value": False,
            "input_type": "checkbox",
        },
    ]
    external.configuration = config
    external.save()


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0075_remove_exit_url"),
    ]

    operations = [migrations.RunPython(update_config, reverse_code=revert_config)]
