# Generated by Django 3.0.14 on 2021-09-30 12:50

import json

from django.db import migrations


def update_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    external = StudyType.objects.get(name="External")
    config = json.loads(external.configuration)
    config["metadata"]["fields"] = [
        {"name": "url", "value": "", "input_type": "url"},
        {
            "name": "scheduling",
            "value": "",
            "options": ["Calendly", "Google Calendar", "Google Form", "Other"],
            "input_type": "radio",
        },
        {
            "name": "study_platform",
            "value": "",
            "options": ["Qualtrics", "Prolific", "Mechanical Turk", "Other"],
            "input_type": "radio",
        },
    ]
    external.configuration = config
    external.save()


def revert_config(apps, schema_editor):
    StudyType = apps.get_model("studies.StudyType")
    external = StudyType.objects.get(name="External")
    config = json.loads(external.configuration)
    config["metadata"]["fields"] = [{"name": "url", "value": "", "input_type": "url"}]
    external.configuration = config
    external.save()


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0076_update_external_study_type"),
    ]

    operations = [migrations.RunPython(update_config, reverse_code=revert_config)]
