# Generated by Django 3.1.13 on 2021-11-12 19:22

from django.db import migrations, models

import studies.models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0078_study_exit_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="conditions",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="response",
            name="exp_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="response",
            name="global_event_timings",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="study",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="study",
            name="structure",
            field=models.JSONField(default=studies.models.default_study_structure),
        ),
        migrations.AlterField(
            model_name="studylog",
            name="extra",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="studytype",
            name="configuration",
            field=models.JSONField(default=studies.models.default_configuration),
        ),
    ]
