# Generated by Django 3.2.11 on 2022-02-23 17:32

import re

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    LabModel = apps.get_model("studies", "Lab")
    db_alias = schema_editor.connection.alias
    labs = LabModel.objects.using(db_alias).only("name").all()
    print()
    for lab in labs:
        slug = lab.name.lower()
        slug = re.sub(r"[^a-z\s\.]", "", slug)
        slug = re.sub(r"\s+", "-", slug)
        lab.slug = slug
        lab.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0079_update_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="slug",
            field=models.SlugField(
                default=None, max_length=255, null=True, unique=True
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
