# Generated by Django 3.2.11 on 2022-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0079_update_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="preview_summary",
            field=models.CharField(default="", max_length=500),
        ),
    ]
