# Generated by Django 3.2.11 on 2022-02-21 15:52

import re

from django.db import migrations, models


def data(apps, schema_editor):
    StudyModel = apps.get_model("studies", "Study")
    db_alias = schema_editor.connection.alias
    # The performance doesn't seem to get better when you add "preview_summary" to the only list.
    studies = StudyModel.objects.using(db_alias).only("short_description").all()

    for study in studies:
        sentences_and_delimiters = re.split(r"(\.\s|\?\s|!\s)", study.short_description)
        first_sentence_with_delimiter = ("").join(sentences_and_delimiters[:2])

        # limit the string to 500 chars as per the field's max length
        study.preview_summary = (
            "${first_sentence_with_delimiter}..."
            if len(first_sentence_with_delimiter) > (500 - 3)
            else first_sentence_with_delimiter
        )
        study.save()


def reverse_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0079_update_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="preview_summary",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.RunPython(data, reverse_code=reverse_data),
    ]
