# Generated by Django 3.2.11 on 2022-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0083_add_study_comments_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="status_change_date",
            field=models.DateTimeField(null=True),
        ),
    ]
