# Generated by Django 3.2.11 on 2022-12-01 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0085_study_comments_extra_set_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="priority",
            field=models.IntegerField(
                default=99,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
    ]
