# Generated by Django 3.2.11 on 2023-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0089_alter_lab_slug"),
    ]

    def alter_study_summaries_over_char_limit(apps, schema_editor):
        Study = apps.get_model("studies", "Study")
        for study in Study.objects.all():
            if len(study.preview_summary) > 300:
                print("\n" + str(study.id) + ": " + study.name)
                # copy the whole preview summary into the study description so that nothing is lost
                study.short_description = (
                    f"{study.preview_summary}\n{study.short_description}"
                )
                # trim the study preview summary and add '...' to indicate that it has been trimmed
                study.preview_summary = f"{study.preview_summary[:297]}..."
                study.save()

    def undo_study_summary_description_changes(apps, schema_editor):
        # find studies where the preview summary ends with "..." and matches the text at the start of the short description
        Study = apps.get_model("studies", "Study")
        for study in Study.objects.all():
            includes_ellipses = study.preview_summary[297:] == "..."
            matches_description = (
                study.preview_summary[:297] == study.short_description[:297]
            )
            if includes_ellipses and matches_description:
                print("\n" + str(study.id) + ": " + study.name)
                # get the matching text up to the first newline character, copy it into the preview summary, and remove it from the short description
                original_preview_summary_end = study.short_description.find("\n", 300)
                if original_preview_summary_end != -1:
                    study.preview_summary = study.short_description[
                        :original_preview_summary_end
                    ]
                    study.short_description = study.short_description[
                        original_preview_summary_end:
                    ]
                    study.save()

    operations = [
        migrations.RunPython(
            alter_study_summaries_over_char_limit,
            reverse_code=undo_study_summary_description_changes,
        ),
        migrations.AlterField(
            model_name="study",
            name="preview_summary",
            field=models.CharField(default="", max_length=300),
        ),
    ]
