# Generated by Django 3.2.11 on 2023-06-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0090_alter_study_preview_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="recording_method",
            field=models.CharField(default="pipe", max_length=50),
        ),
    ]
