# Generated by Django 3.2.11 on 2023-08-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0091_response_recording_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="pipe_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
