# Generated by Django 3.2.11 on 2023-11-02 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0093_remove_studytype_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="eligibility",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Eligible", "Eligible"),
                        ("Ineligible_TooYoung", "Ineligible_TooYoung"),
                        ("Ineligible_TooOld", "Ineligible_TooOld"),
                        (
                            "Ineligible_CriteriaExpression",
                            "Ineligible_CriteriaExpression",
                        ),
                        ("Ineligible_Participation", "Ineligible_Participation"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
