# Generated by Django 3.2.11 on 2023-08-30 15:35

from django.db import migrations


def add_jspysch(apps, schema_editor):
    apps.get_model("studies", "StudyType")(id=3, name="jsPsych").save()


def remove_jspych(apps, schema_editor):
    apps.get_model("studies", "StudyType").objects.get(id=3).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0093_remove_studytype_configuration"),
    ]

    operations = [migrations.RunPython(add_jspysch, reverse_code=remove_jspych)]
