# Generated by Django 3.2.11 on 2023-08-30 15:35

from django.db import migrations


def add_jspsych(apps, schema_editor):
    apps.get_model("studies", "StudyType")(id=3, name="jsPsych").save()


def remove_jspsych(apps, schema_editor):
    apps.get_model("studies", "StudyType").objects.get(id=3).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0094_add_response_eligibility_default_criteria_expression"),
    ]

    operations = [migrations.RunPython(add_jspsych, reverse_code=remove_jspsych)]
