# Generated by Django 3.2.11 on 2024-02-28 20:14

from django.db import migrations, models

import studies.models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0096_response_survey_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="exit_url",
            field=models.URLField(default=studies.models.default_exit_url),
        ),
    ]
