# Generated by Django 3.2.11 on 2024-01-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0096_response_survey_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='language',
            field=models.TextField(choices=[('en', 'English'), ('am', 'Amharic'), ('bn', 'Bengali'), ('bho', 'Bhojpuri'), ('my', 'Burmese'), ('ceb', 'Cebuano'), ('hne', 'Chhattisgarhi'), ('nl', 'Dutch'), ('egy', 'Egyptian Spoken Arabic'), ('fr', 'French'), ('gan', 'Gan'), ('de', 'German'), ('gu', 'Gujarati'), ('hak', 'Hakka'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('ig', 'Igbo'), ('id', 'Indonesian'), ('pes', 'Iranian Persian'), ('it', 'Italian'), ('ja', 'Japanese'), ('jv', 'Javanese'), ('cjy', 'Jinyu'), ('kn', 'Kannada'), ('km', 'Khmer'), ('ko', 'Korean'), ('mag', 'Magahi'), ('mai', 'Maithili'), ('ms', 'Malay'), ('ml', 'Malayalam'), ('cmn', 'Chinese (Mandarin)'), ('mr', 'Marathi'), ('nan', 'Min Nan'), ('mor', 'Moroccan Spoken Arabic'), ('pbu', 'Northern Pashto'), ('uzn', 'Northern Uzbek'), ('or', 'Odia'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('skr', 'Saraiki'), ('sd', 'Sindhi'), ('so', 'Somali'), ('es', 'Spanish'), ('su', 'Sunda'), ('tl', 'Tagalog'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('lah', 'Western Punjabi'), ('wuu', 'Wu'), ('hsn', 'Xiang Chinese'), ('yo', 'Yoruba'), ('yue', 'Chinese (Cantonese)')], default='en'),
        ),
    ]
