# Generated by Django 3.2.25 on 2024-11-12 18:30

from django.db import migrations, models

EFP = 1
EXTERNAL = 2
JSPSYCH = 3


def populate_recording_method(apps, schema_editor):
    responses = apps.get_model("studies", "Response").objects.filter(
        recording_method=None
    )
    for response in responses:
        if response.study_type.id == EXTERNAL:
            response.recording_method = None
        elif response.study_type.id == JSPSYCH:
            response.recording_method = "jspsych"
        elif response.study_type.id == EFP:
            if response.videos.count() > 0 and all(
                v.pipe_name is not None for v in response.videos.all()
            ):
                response.recording_method = "pipe"
        response.save()


def do_nothing(apps, schema_editor):
    """There is nothing to undo with this migration."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0099_alter_response_recording_method"),
    ]

    operations = [
        migrations.RunPython(populate_recording_method, reverse_code=do_nothing),
        migrations.AlterField(
            model_name="response",
            name="recording_method",
            field=models.CharField(default="pipe", max_length=50, null=True),
        ),
    ]
