# Generated by Django 3.2.25 on 2025-02-04 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0100_alter_response_recording_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="completed",
            new_name="completed_exit_frame",
        ),
    ]
