# Generated by Django 3.2.25 on 2025-03-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0100_alter_response_recording_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="researcher_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("review", "Needs review"),
                    ("to_pay", "To pay"),
                    ("do_not_pay", "Do not pay"),
                    ("paid", "Paid"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="researcher_session_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("to_schedule", "To schedule"),
                    ("scheduled", "Scheduled"),
                    ("session_attended", "Session attended"),
                    ("session_complete", "Session complete"),
                    ("follow_up", "Follow up"),
                    ("communication_complete", "Communication complete"),
                    ("withdrawn_closed", "Withdrawn or closed"),
                ],
                max_length=22,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="researcher_star",
            field=models.BooleanField(default=False),
        ),
    ]
