# Generated by Django 3.2.25 on 2025-03-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0100_alter_response_recording_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="researcher_payment_status",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("paid", "Paid"), ("nopay", "Do Not Pay")],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="researcher_response_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("pending", "Pending"),
                    ("underrev", "Under Review"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="researcher_star",
            field=models.BooleanField(default=False),
        ),
    ]
