# Generated by Django 5.2.1 on 2025-05-30 05:19
from django.db import migrations, models


def lowercase_images(apps, schema_editor):
    Study = apps.get_model("studies", "Study")
    db_alias = schema_editor.connection.alias
    Study.objects.using(db_alias).filter(image__regex="[A-Z]").update(
        image=models.functions.Lower("image")
    )


def restore_images(apps, schema_editor):
    # This is a stub.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0101_add_researcher_editable_fields_to_response"),
    ]

    operations = [
        migrations.RunPython(lowercase_images, reverse_code=restore_images),
    ]
