# Generated by Django 5.2.1 on 2025-06-10 21:20

from django.db import migrations
from django.db.models.functions import Lower


def lowercase_images(apps, schema_editor):
    Lab = apps.get_model("studies", "Lab")
    db_alias = schema_editor.connection.alias
    # if badge image path has uppercase, convert to lowercase
    Lab.objects.using(db_alias).filter(badge__regex="[A-Z]").update(
        badge=Lower("badge")
    )
    # if banner image path has uppercase, convert to lowercase
    Lab.objects.using(db_alias).filter(banner__regex="[A-Z]").update(
        banner=Lower("banner")
    )


def restore_images(apps, schema_editor):
    # This is a stub.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0102_lowercase_study_image_filename"),
    ]

    operations = [
        migrations.RunPython(lowercase_images, reverse_code=restore_images),
    ]
