# Generated by Django 5.2.2 on 2025-06-30 23:22

import json

from django.db import migrations


def add_kwargs_to_video_cleanup_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    bucket_names = [
        "S3_BUCKET_NAME",
        "JSPSYCH_S3_BUCKET",
    ]

    try:
        task = PeriodicTask.objects.get(name="Nightly video upload cleanup")
        task.kwargs = json.dumps({"bucket_names": bucket_names})
        task.save()
    except PeriodicTask.DoesNotExist:
        pass


def remove_kwargs_from_video_cleanup_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Nightly video upload cleanup")
        task.kwargs = ""
        task.save()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0103_lowercase_lab_badge_banner_images"),
    ]

    operations = [
        migrations.RunPython(
            add_kwargs_to_video_cleanup_task, remove_kwargs_from_video_cleanup_task
        ),
    ]
