# Generated by Django 5.2.9 on 2026-02-03 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0104_add_bucket_kwarg_to_video_cleanup"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="consentruling",
            new_name="studies_con_respons_23a801_idx",
            old_fields=("response", "action"),
        ),
        migrations.RenameIndex(
            model_name="consentruling",
            new_name="studies_con_respons_df509e_idx",
            old_fields=("response", "arbiter"),
        ),
        migrations.RenameIndex(
            model_name="studylog",
            new_name="studies_stu_study_i_b16384_idx",
            old_fields=("study", "action"),
        ),
        migrations.AddField(
            model_name="study",
            name="max_responses",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
